version: '3'
services:
  tweet-stream-server:
    build:
      context: server/
      dockerfile: server.Dockerfile
    ports:
      - "9999:9999"
  tweet-stream-client:
    build:
      context: client/
      dockerfile: client.Dockerfile
    depends_on:
      - tweet-stream-server
    command: ["./scripts/wait-for-it.sh", "tweet_stream_server:9999", "--", "python", "client.py"]
  redis:
      image: redis
      ports:
        - "6379:6379"
  web-server:
    build:
      context: web_server/
      dockerfile: web_server.Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - redis
