apiVersion: v1
kind: Service
metadata:
  name: reddit-stream-server
  labels:
    app: reddit-stream-server
spec:
  selector:
    app: reddit-stream-server
  type: NodePort
  ports:
  - port: 9998
    nodePort: 30008
    protocol: TCP