apiVersion: v1
kind: Service
metadata:
  name: tweet-stream-server
  labels:
    app: tweet-stream-server
spec:
  selector:
    app: tweet-stream-server
  type: NodePort
  ports:
  - port: 9999
    nodePort: 30009
    protocol: TCP