# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class TestServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TestCall = channel.unary_stream(
        '/stream.TestService/TestCall',
        request_serializer=test__pb2.TestRequest.SerializeToString,
        response_deserializer=test__pb2.TestResponse.FromString,
        )


class TestServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TestCall(self, request, context):
    """an example of getting a feature
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TestCall': grpc.unary_stream_rpc_method_handler(
          servicer.TestCall,
          request_deserializer=test__pb2.TestRequest.FromString,
          response_serializer=test__pb2.TestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stream.TestService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
